### ISSUE TITLE
Typo (?) on line 175

### ISSUE THREAD

**Issue by lmartak** [ycpei/ypei.me#1]
On [this line](https://github.com/ycpei/ypei.me/blame/master/posts/2019-02-14-raise-your-elbo.md#L175), there is a parenthesis typo.

> So `$\sum_i L(p(x_{i}), z_{i}; \theta)$` is non-decreasing at both the
E-step and the M-step.

I assume `\sum_i L(p(x_{i}), z_{i}; \theta)` ought to be  `\sum_i L(p(x_{i}, z_{i}; \theta))`.

Please correct me with explanation if I'm just wrong and don't get the intended meaning.

**Comment by ycpei** [comment]
Thank you. I just fixed it.
